### PR TITLE
Create installation-manual-failover.md

### PR DESCRIPTION
**Pull request by MaxCentreon**
## Description

New documentation for manual failover installation

## Target serie

- [x] 20.04.x
- [x] 20.10.x (master)

### CODE REVIEW

**Comment by omercier** [comment]
* This new page must be indexed in the fr/sidebars.json file
* What about the English version? We should at least create it, mentioning that it is not yet available and pointing to the French version, I think.

**Comment by cgagnaire** [comment]
@Sims24 @omercier Is this PR ok?

**Comment by omercier** [comment]
Woops! 1 year! Is this PR still relevant? @Sims24 @MaxCentreon

**Comment by cedricmeschin** [comment]
Duplicate by https://github.com/centreon/centreon-documentation/pull/1585

**Pull request closed without merging**
