### PR TITLE
fix(installation): typo in web installation links

### PR DESCRIPTION
**Pull request by oliryde**
Let me know if the commit message needs a specific format and I will change it.

### CODE REVIEW

**Comment by Moujimouja** [comment]
Thanks for contributing, you can have a commit formatted like that, it would be perfect 

fix(installation): typo in web installation links

**Comment by oliryde** [comment]
@Moujimouja I made a new commit with the requested change.

**Comment by oliryde** [comment]
Thank you for the prompt response @Moujimouja.
I will make sure to make more pull requests if I encounter anything else.

**Comment by Moujimouja** [comment]
You're more than welcome to help us :) 

FYI the documentation is now up to date with your changes ;) 

Have a nice day

**Pull request merged**
