### PR TITLE
migrate to docusaurus v2 - applications dynamics ax mssql v2

### PR DESCRIPTION
**Pull request by Tpo76**
## Description

Migrate docusorus v1 to v2 format
https://github.com/centreon/centreon-documentation/pull/1260

## Target version

- [ ] 20.10.x
- [ ] 21.04.x
- [x] 21.10.x
- [ ] 22.04.x (next)

### CODE REVIEW

**Review by Sims24 — APPROVED** [review]

**Comment by Sims24** [comment]
We cannot merge this as it is based upon old layout. Please re-issue a PR within the dedicated section. 

I don't delete your branch so you can easily jump from one to another. 

Best

**Comment by Tpo76** [comment]
New branch is for git No0b 😛 
I should have included the first sidebar sync in my staging merge, but it worked too

**Comment by Sims24** [comment]
No, you need to use the script and create a new PR.

**Comment by Tpo76** [comment]
But the script do not manage dyn-mode plugins or did that change?
Because this plugin is a dyn-mode one.

**Pull request closed without merging**
