### PR TITLE
add(epp): applications-dynamics-ax-mssql

### PR DESCRIPTION
**Pull request by Tpo76**
## Description

Init dock for Applications-Dynamics-Ax-Mssql

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [x] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x (master)

### CODE REVIEW

**Comment by Sims24** [comment]
@Tpo76 follow latest guidelines to move this to Docusaurus v2 format please

**Comment by Tpo76** [comment]
#1351

**Comment by cg-tw** [comment]
Closed by https://github.com/centreon/centreon-documentation/pull/1351

**Comment by cg-tw** [comment]
Closed by https://github.com/centreon/centreon-documentation/pull/1351

**Pull request closed without merging**
