### PR TITLE
Enh monitor a linux server with snmp

### PR DESCRIPTION
**Pull request by cedricmeschin**
## Description

Rewrite monitor first Linux host with SNMP on a dedicated page.

## Target serie

- [ ] 20.04.x
- [ ] 20.10.x
- [ ] 21.04.x
- [X] 21.10.x
- [X] 22.04.x (master)

### CODE REVIEW

**Review by pkriko — APPROVED** [review]
Hello @cg-tw , I'm kind of fan of the format.
I didn't review the english/grammar. But the content seems enough explicit no ?
What are your thoughts ?

**Review by cg-tw — DISMISSED** [review]

**Comment by cedricmeschin** [comment]
Hi,
I've missed adding a screenshot.

**Review by pkriko — APPROVED** [review]
waiting for @cg-tw about the english.
Seems good for the "technical" things.

**Review by cg-tw — APPROVED** [review]

**Review by cg-tw — CHANGES_REQUESTED** [review]

**Review by cg-tw — APPROVED** [review]

**Review by pkriko — APPROVED** [review]

**Comment by cg-tw** [comment]
closed by https://github.com/centreon/centreon-documentation/pull/1323

**Pull request closed without merging**
