### PR TITLE
enh(doc) for all new layout snmp plugin proc

### PR DESCRIPTION
**Pull request by Tpo76**
## Description

adding mapping between snmpwalk and plugin option.
First, commit with a single proc for validation, all others will be done here if approuved.

## Target version

- [ ] 20.10.x (staging)
- [ ] 21.04.x (staging)
- [ ] 21.10.x (staging)
- [ ] 22.04.x (staging)
- [ ] Cloud (staging)
- [x] Plugin Packs (staging)
- [ ] 22.10.x (next)

### CODE REVIEW

**Comment by Sims24** [comment]
Hi @Tpo76 

Thanks, I think it would be better to put it in the troubleshooting section. Helping users to troubleshoot and configure their probes with SNMPv3, don't you think?

**Comment by Tpo76** [comment]
I thought about the troubleshoot section too but I suddenly doubt 😅

That's why I only did one and not the 70ish up to date plugin with snmp stuff.

But why not troubleshoot section.
Theb a redirect link to that section everywhere we have this yellow box about snmpv3 and EXTRAOPTIONS fields?

Should be quite easy to massively edit it.
Then change the plugin script to auto include that new link.

**Comment by Sims24** [comment]
I don't feel like it's relevant to add it to every single SNMP proc. But it would definitely make sense in a 'How-to-guides', probably more than in the troubleshooting guide 🤔 We could even imagine explicating the dump of all options in the SNMPEXTRAOPTIONS macro at the host level. 

The idea to add a link sounds relevant, for sure ;)

**Review by Sims24 — APPROVED** [review]

**Comment by Sims24** [comment]
I'm so late ! But thanks a lot @Tpo76!

**Review by Sims24 — CHANGES_REQUESTED** [review]
extra <br> I didn't catch at first sight + link doesn't work (see jenkins build). Will take a look.

**Comment by Tpo76** [comment]
Arg... 
Sorry, I didn't check the Jenkins' job as it was working on my local build.

**Comment by Sims24** [comment]
Well, that escalated quickly 🤣 

I will fire a new PR to replace this one.

**Pull request closed without merging**
